# Generated by Django 2.2.7 on 2020-01-06 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riddles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plane',
            name='slug',
            field=models.SlugField(default='new-slug', max_length=128, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plane',
            name='type',
            field=models.CharField(default='type1', max_length=128),
            preserve_default=False,
        ),
    ]
