# Generated by Django 2.2.7 on 2020-01-07 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riddles', '0002_auto_20200106_1315'),
    ]

    operations = [
        migrations.CreateModel(
            name='fly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='plane',
            name='flys',
            field=models.ManyToManyField(to='riddles.fly'),
        ),
    ]
