# Generated by Django 2.2.7 on 2020-01-07 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riddles', '0003_auto_20200108_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fly',
            name='time',
            field=models.CharField(max_length=50),
        ),
    ]
