# Generated by Django 2.2.7 on 2020-01-08 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riddles', '0004_auto_20200108_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plane',
            name='flys',
            field=models.ManyToManyField(related_name='planes', to='riddles.fly'),
        ),
    ]
